In [1]:
import numpy as np

a = np.random.randint(10, size=6)

print('list(a):', list(a))
print('a.tolist():', a.tolist())

b = np.random.randint(10, size=6).reshape(3,2)

print('list(b):', list(b))
print('b.tolist():', b.tolist())

list(a): [1, 4, 3, 7, 4, 7]
a.tolist(): [1, 4, 3, 7, 4, 7]
list(b): [array([2, 0]), array([8, 8]), array([6, 0])]
b.tolist(): [[2, 0], [8, 8], [6, 0]]


In [3]:
'''
list(a) 只會把第一層元素轉換成 List, 多層的話只有第一層會轉; tolist() 才會達成多層型態轉換。
'''

'\nlist(a) 只會把第一層元素轉換成 List, 多層的話只有第一層會轉; tolist() 才會達成多層型態轉換。\n'

In [4]:
import numpy as np
a = np.random.randint(10, size=6)

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[4 8 6 5 1 4]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [5]:
import numpy as np
b = np.random.randint(10, size=(3, 4))

print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[4 2 9 4]
 [3 7 7 2]
 [3 4 0 8]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [6]:
import numpy as np
c = np.random.randint(10, size=(2, 3, 2))

print(c)

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[7 6]
  [8 5]
  [8 8]]

 [[7 6]
  [1 5]
  [7 9]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


In [7]:
def tolist(interable):
    if type(interable) != np.ndarray:
        return interable
    newlist = []
    for obj in interable:
        newlist.append(tolist(obj))
    return list(newlist)
   
print(tolist(a))
print(tolist(b))
print(tolist(c))

[4, 8, 6, 5, 1, 4]
[[4, 2, 9, 4], [3, 7, 7, 2], [3, 4, 0, 8]]
[[[7, 6], [8, 5], [8, 8]], [[7, 6], [1, 5], [7, 9]]]
